name: Nuget

env:
  ProjectPath: src/Cord.SDK
  ProjectName: Cord.SDK
  TagName: Cord.SDK

on:
  push:
    tags:
      - "*.*.*"
      - "*.*.*-RC*"


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Version from TagName
        run: echo "VERSION=$GITHUB_REF_NAME" >> $GITHUB_ENV
      
      - name: Print Version
        run: echo ${VERSION}

      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION}

      - name: Pack
        run: dotnet pack ${{env.ProjectPath}}/${{env.ProjectName}}.csproj --configuration Release /p:Version=${VERSION} --no-build --output .

      # - name: Push
      #   run: dotnet nuget push "*.nupkg" --source https://api.nuget.org/v3/index.json --api-key ${NUGET_API_KEY}
      #   env:
      #     NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
